version: '3.8'
services:
  api:
    build: ./api
    container_name: api
    ports:
      - '5000:5000'
  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '3000:3000'